# Generated by Django 5.2 on 2025-05-11 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(limit_choices_to={'role': 'assignee'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
